# This file was generated by GoReleaser. DO NOT EDIT.
class Demo < Formula
  desc "Jenkins CLI allows you manage your Jenkins as an easy way"
  homepage "https://github.com/jenkins-zh/jenkins-cli"
  version "0.0.9"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/LinuxSuRen/go-demo/releases/download/v0.0.9/go-demo_0.0.9_Darwin_x86_64.tar.gz"
    sha256 "955c3ab3e54e933414015987e77d59eb5e4e61dbd4b3abf517730c60489c9b29"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/LinuxSuRen/go-demo/releases/download/v0.0.9/go-demo_0.0.9_Linux_x86_64.tar.gz"
      sha256 "09715ae39d51840614ecb4fbeb83ec5d116418d8a985f0c060ed8d05bf5d80fe"
    end
  end

  def install
    bin.install name
    
    # Install bash completion
    output = Utils.popen_read("#{bin}/jcli completion")
    (bash_completion/"jcli").write output
    
    # Install zsh completion
    output = Utils.popen_read("#{bin}/jcli completion --type zsh")
    (zsh_completion/"_jcli").write output
    
    prefix.install_metafiles
  end

  test do
    version_output = shell_output("#{bin}/jcli version")
    assert_match version.to_s, version_output
  end
end
